sudo: false
dist: trusty
language: python
cache: pip
python: 3.6
script: make test

install:
  - pip install -U pip setuptools wheel
  - pip install -r requirements.txt

services:
  - postgresql

addons:
  postgresql: 9.6
