# Generated by Django 2.0.3 on 2018-04-12 20:15

import cfp.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('talk', 'A talk (25 minutes)'), ('workshop', 'A workshop (3 hours)'), ('poster', 'A poster'), ('other', 'Something else')], max_length=40)),
                ('title', models.CharField(max_length=60)),
                ('subtitle', models.CharField(blank=True, max_length=120)),
                ('copresenter_names', models.TextField(blank=True)),
                ('description', models.TextField(validators=[cfp.validators.validate_max_300_words])),
                ('outline', models.TextField(validators=[cfp.validators.validate_max_300_words])),
                ('aimed_at_new_programmers', models.BooleanField()),
                ('aimed_at_teachers', models.BooleanField()),
                ('aimed_at_data_scientists', models.BooleanField()),
                ('would_like_mentor', models.BooleanField()),
                ('would_like_longer_slot', models.BooleanField()),
                ('state', models.CharField(blank=True, max_length=40)),
                ('track', models.CharField(blank=True, max_length=40)),
                ('special_reply_required', models.BooleanField(default=False)),
                ('scheduled_room', models.CharField(blank=True, max_length=40)),
                ('scheduled_time', models.DateTimeField(null=True)),
                ('coc_conformity', models.BooleanField()),
                ('ticket', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('review_proposal', 'Can review proposals')],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_interested', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfp.Proposal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('proposal', 'user')},
        ),
    ]
