# Generated by Django 2.0.3 on 2018-05-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='equipment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='session_type',
            field=models.CharField(choices=[('talk', 'A talk (25 minutes)'), ('workshop', 'A workshop (3 hours)'), ('poster', 'A poster'), ('kidsworkshop', 'Education Summit workshop for young coders (Saturday, 50 mins)'), ('teachersworkshop', 'Education Summit workshop for educators (Sunday, 50 mins)'), ('teacherstalk', 'Education Summit talk for educators (Sunday, 25 mins)'), ('other', 'Something else')], max_length=40),
        ),
    ]
