# Generated by Django 2.0.3 on 2018-06-15 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0002_add_education_and_equipment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={'permissions': [('review_proposal', 'Can review proposals'), ('review_education_proposal', 'Can review education proposals')]},
        ),
    ]
