# Generated by Django 2.0.3 on 2018-06-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0003_add_education_reviewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='state',
            field=models.CharField(blank=True, choices=[('accept', 'Accepted'), ('reject', 'Plan to Reject'), ('withdrawn', 'Withdrawn')], max_length=40),
        ),
    ]
