# Generated by Django 2.0.3 on 2018-07-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0004_add_proposal_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='confirmed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='state',
            field=models.CharField(blank=True, choices=[('confirm', 'Confirmed'), ('cancel', 'Cancelled'), ('accept', 'Accepted'), ('reject', 'Plan to Reject'), ('withdrawn', 'Withdrawn')], max_length=40),
        ),
    ]
