# Generated by Django 2.0.3 on 2018-07-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0005_allow_proposal_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='replied_to',
            field=models.DateTimeField(null=True),
        ),
    ]
