# Generated by Django 2.0.3 on 2018-08-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0007_changes_for_scheduling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='state',
            field=models.CharField(blank=True, choices=[('confirm', 'Confirmed'), ('cancel', 'Cancelled'), ('accept', 'Accepted'), ('reject', 'Plan to Reject'), ('withdrawn', 'Withdrawn'), ('placeholder', 'Schedule Placeholder')], max_length=40),
        ),
    ]
