# Generated by Django 2.0.3 on 2018-07-25 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0007_add_fields_for_scheduler'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='all_rooms_event',
            new_name='break_event',
        ),
    ]
