# Generated by Django 2.0.3 on 2018-09-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfp', '0008_add_schedule_placeholder_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='description',
            field=models.TextField(),
        ),
    ]
