# Generated by Django 2.0.3 on 2018-08-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DinnerTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinner', models.CharField(choices=[('CD', 'Conference Dinner at City Hall on Saturday 15th September'), ('CLSA', 'The Clink on Saturday 15th September'), ('CLSU', 'The Clink on Sunday 16th September'), ('CLMO', 'The Clink on Monday 17th September'), ('CLTU', 'The Clink on Tuesday 18th September'), ('CLWE', 'The Clink on Wednesday 19th September')], max_length=4)),
                ('starter', models.CharField(choices=[('ENB', 'Egg and bacon'), ('ESB', 'Egg, sausage and bacon'), ('SESS', 'Spam, egg, Spam, Spam, bacon and Spam'), ('SSSE', 'Spam, Spam, Spam, egg and Spam')], max_length=4)),
                ('main', models.CharField(choices=[('ENS', 'Egg and Spam'), ('EBS', 'Egg, bacon and Spam'), ('SSSS', 'Spam, Spam, Spam, Spam, Spam, Spam, baked beans, Spam, Spam, Spam and Spam'), ('LTAC', 'Lobster Thermidor aux crevettes with a Mornay sauce, garnished with truffle pâté, brandy and a fried egg on top, and Spam.')], max_length=4)),
                ('dessert', models.CharField(choices=[('EBSS', 'Egg, bacon, sausage and Spam'), ('SBSS', 'Spam, bacon, sausage and Spam'), ('ENB', 'Egg and bacon'), ('ESB', 'Egg, sausage and bacon')], max_length=4)),
                ('cost_excl_vat', models.IntegerField()),
            ],
        ),
    ]
