# Generated by Django 2.0.3 on 2018-09-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DinnerTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinner', models.CharField(choices=[('CLSA', 'The Clink on Saturday 15th September'), ('CLSU', 'The Clink on Sunday 16th September'), ('CLMO', 'The Clink on Monday 17th September'), ('CLTU', 'The Clink on Tuesday 18th September'), ('CLWE', 'The Clink on Wednesday 19th September'), ('CD', 'Conference Dinner at City Hall on Saturday 15th September')], max_length=4)),
                ('starter', models.CharField(choices=[('SOTD', 'Soup of the Day, sour dough bread (vg)'), ('STRC', 'Smoked trout rillette coated in a citrus crumb, trio of beetroot, with radicchio salad'), ('BCBB', 'Blue cheese bon bons, banana puree roast walnuts, balsamic reduction, frisee salad (v)'), ('RORS', 'Rillette of oak roast scottish salmon with ogen melon & gooseberry cream'), ('HTRP', 'Heritage tomato and roasted pepper soup with sippets (vg/gf on request at the table)')], max_length=4)),
                ('main', models.CharField(choices=[('PSST', 'Pan seared sea trout, sea bass and plaice fillet, shellfish broth, spring onion, saffron aioli'), ('RPFC', 'Roast pork fillet with crispy belly, sage mash, apple puree, charred baby carrots'), ('FMP', 'Forest mushroom parcel, wilted greens, tarragon broth (vg)'), ('RGBR', 'Rosemary and garlic braised rump of Welsh lamb in a rich red wine jus served with champ mash'), ('RSBL', 'Roast sea bass served with a laverbread and orange butter sauce & cockles'), ('RVTT', 'Roasted vegetable tian with sunblushed tomato sauce (vg)')], max_length=4)),
                ('dessert', models.CharField(choices=[('ICP', 'Iced caramel parfait, sable biscuit, crisp meringue and autumn berries'), ('RPPP', 'Rice pudding, pistachio praline, damson compote (vg)'), ('TLT', 'Tangy lemon tart with orange and ginger syrup and lavender ice cream'), ('APS', 'Apple pie served with elderflower sorbet (vg, gf)')], max_length=4)),
            ],
        ),
    ]
