# Generated by Django 2.0.3 on 2018-08-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0002_dinnerticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinnerticket',
            name='cost_excl_vat',
        ),
        migrations.AlterField(
            model_name='dinnerticket',
            name='dinner',
            field=models.CharField(choices=[('CLSA', 'The Clink on Saturday 15th September'), ('CLSU', 'The Clink on Sunday 16th September'), ('CLMO', 'The Clink on Monday 17th September'), ('CLTU', 'The Clink on Tuesday 18th September'), ('CLWE', 'The Clink on Wednesday 19th September'), ('CD', 'Conference Dinner at City Hall on Saturday 15th September')], max_length=4),
        ),
    ]
