# Generated by Django 2.0.3 on 2018-04-14 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_requested', models.IntegerField()),
                ('would_like_ticket_set_aside', models.BooleanField()),
                ('sat', models.BooleanField()),
                ('sun', models.BooleanField()),
                ('mon', models.BooleanField()),
                ('tue', models.BooleanField()),
                ('wed', models.BooleanField()),
                ('about_you', models.TextField()),
                ('amount_offered', models.IntegerField(default=0)),
                ('requested_ticket_only', models.BooleanField(default=False)),
                ('special_reply_required', models.BooleanField(default=False)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grant_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
