# Generated by Django 2.0.3 on 2018-07-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='amount_awarded',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ticket_awarded',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
