# Generated by Django 2.0.3 on 2018-07-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0003_application_replied_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_declined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='full_amount_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='amount_awarded',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
