# Generated by Django 2.0.3 on 2018-07-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_badge_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='badge_company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='badge_pronoun',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='badge_snake_colour',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='badge_snake_extras',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='badge_twitter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
