# Generated by Django 2.0.3 on 2018-08-11 17:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_make_badge_fields_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ical_token',
            field=models.CharField(default='u6O3MdCU62WQDEOp7qwIeqgk', max_length=24),
        ),
        migrations.AddField(
            model_name='user',
            name='items_of_interest',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
