# Generated by Django 2.0.3 on 2018-08-17 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_add_free_ticket_permission'),
        ('accounts', '0004_ical_and_interest_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected', models.DateTimeField(null=True)),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badge', to='tickets.Ticket')),
            ],
        ),
    ]
