# Generated by Django 2.0.3 on 2018-08-18 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_badge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('reg_desk_assistant', 'Registration Desk Assistant')]},
        ),
    ]
