# Generated by Django 2.0.3 on 2018-09-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
