# Generated by Django 2.0.3 on 2018-07-28 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cfp', '0007_changes_for_scheduling'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('has_sttr', models.BooleanField()),
                ('has_projector', models.BooleanField()),
                ('has_screen', models.BooleanField()),
                ('has_vga', models.BooleanField()),
                ('has_hdmi', models.BooleanField()),
                ('has_lectern', models.BooleanField()),
                ('has_mic', models.BooleanField()),
                ('has_stage', models.BooleanField()),
                ('has_fixed_seating', models.BooleanField()),
                ('accessible_auditorium', models.BooleanField()),
                ('accessible_stage', models.BooleanField()),
                ('accessibility_notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True, null=True)),
                ('length', models.DurationField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='cfp.Proposal')),
                ('additional_people', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('chair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chaired_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('day', models.DateField()),
                ('order', models.PositiveIntegerField()),
                ('visible', models.BooleanField(default=False)),
                ('stream_type', models.CharField(choices=[('day', 'Daytime'), ('eve', 'Evening')], max_length=3)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='schedule.Room')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='schedule.Stream'),
        ),
    ]
