# Generated by Django 2.0.3 on 2018-07-22 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cfp', '0006_proposal_replied_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField()),
                ('has_sttr', models.BooleanField()),
                ('has_projector', models.BooleanField()),
                ('has_screen', models.BooleanField()),
                ('has_vga', models.BooleanField()),
                ('has_hdmi', models.BooleanField()),
                ('has_lectern', models.BooleanField()),
                ('has_mic', models.BooleanField()),
                ('has_stage', models.BooleanField()),
                ('has_fixed_seating', models.BooleanField()),
                ('accessible_auditorium', models.TextField()),
                ('accessible_stage', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('length', models.DurationField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='cfp.Proposal')),
                ('additional_people', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('chair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chaired_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('day', models.CharField(choices=[('tue', 'Tuesday'), ('sat', 'Saturday'), ('mon', 'Monday'), ('wed', 'Wednesday'), ('sun', 'Sunday')], max_length=3)),
                ('visible', models.BooleanField()),
                ('stream_type', models.CharField(choices=[('day', 'Daytime'), ('eve', 'Evening')], max_length=3)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='schedule.Room')),
            ],
        ),
    ]
