# Generated by Django 2.0.3 on 2018-08-11 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cfp', '0008_add_schedule_placeholder_state'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session_name', models.CharField(blank=True, max_length=30, null=True)),
                ('time', models.TimeField()),
                ('duration', models.DurationField()),
                ('event_type', models.CharField(choices=[('pre-allocated', 'Pre-allocated'), ('talk', 'Talk'), ('workshop', 'Workshop'), ('kidsworkshop', 'Kids Workshop'), ('teachersworkshop', 'Teachers Workshop'), ('teacherstalk', 'Teachers Talk')], max_length=30)),
                ('visible', models.BooleanField()),
                ('scheduler_linked', models.BooleanField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='schedule.Room')),
            ],
        ),
        migrations.CreateModel(
            name='SlotEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True, null=True)),
                ('length', models.DurationField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='cfp.Proposal')),
                ('additional_people', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('chair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chaired_slots', to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='schedule.Slot')),
            ],
        ),
        migrations.RemoveField(
            model_name='session',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='session',
            name='additional_people',
        ),
        migrations.RemoveField(
            model_name='session',
            name='chair',
        ),
        migrations.RemoveField(
            model_name='session',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='room',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='Stream',
        ),
    ]
