# Generated by Django 2.0.3 on 2018-08-11 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_match_scheduler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotevent',
            name='length',
        ),
        migrations.RemoveField(
            model_name='slotevent',
            name='time',
        ),
    ]
