# Generated by Django 2.0.3 on 2018-07-22 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20180722_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='schedule.Stream'),
        ),
        migrations.AlterField(
            model_name='session',
            name='additional_people',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stream',
            name='day',
            field=models.CharField(choices=[('wed', 'Wednesday'), ('mon', 'Monday'), ('tue', 'Tuesday'), ('sun', 'Sunday'), ('sat', 'Saturday')], max_length=3),
        ),
    ]
