# Generated by Django 2.0.3 on 2018-08-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_remove_unused_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=24, unique=True)),
                ('value', models.TextField(null=True)),
            ],
        ),
    ]
