# Generated by Django 2.0.3 on 2018-08-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotevent',
            name='ical_id',
            field=models.CharField(default='invalid', max_length=8),
            preserve_default=False,
        ),
    ]
