# Generated by Django 2.0.3 on 2018-07-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20180722_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
