# Generated by Django 2.0.3 on 2018-04-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketinvitation',
            name='email_addr',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='ticketinvitation',
            name='token',
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
