# Generated by Django 2.0.3 on 2018-07-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_make_token_better_and_email_non_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='free_reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
