# Generated by Django 2.0.3 on 2018-07-08 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_free_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': [('create_free_ticket', 'Can create free tickets')]},
        ),
    ]
