# Generated by Django 2.0.3 on 2018-06-17 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='content_type',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
    ]
